<?php

return [

    /*
    |--------------------------------------------------------------------------
    | eSIM device compatibility lists
    |--------------------------------------------------------------------------
    |
    | Powers the "Check compatibility" modal on the eSIM store page. iOS is a
    | flat list; Android is grouped by manufacturer (case-insensitive brands
    | merged). A device must support eSIM, be carrier-unlocked, and not be
    | jailbroken/rooted to install an eSIM.
    |
    */

    'ios' => [
        'iPad 10th Gen',
        'iPad 8th Gen (WiFi+Cellular)',
        'iPad Air 11-inch (M2)',
        'iPad Air 13-inch (M2)',
        'iPad Air 3rd Gen',
        'iPad Air 4th Gen (WiFi+Cellular)',
        'iPad Air 5th Gen (WiFi+Cellular)',
        'iPad mini (6th Gen)',
        'iPad mini 5th Gen',
        'iPad Pro 11 inch 3rd Gen',
        'iPad Pro 11 inch 3rd Gen (1TB, WiFi+Cellular)',
        'iPad Pro 11 inch 3rd Gen (WiFi+Cellular)',
        'iPad Pro 11 inch 4th Gen',
        'iPad Pro 11 inch 4th Gen (WiFi+Cellular)',
        'iPad Pro 11-inch (M4)',
        'iPad Pro 12.9 inch 3rd Gen (1TB, WiFi+Cellular)',
        'iPad Pro 12.9 inch 3rd Gen (WiFi+Cellular)',
        'iPad Pro 12.9 inch 4th Gen (WiFi+Cellular)',
        'iPad Pro 12.9 inch 5th Gen',
        'iPad Pro 12.9 inch 6th Gen',
        'iPad Pro 13-inch (M4)',
        'iPhone 11',
        'iPhone 11 Pro',
        'iPhone 11 Pro Max',
        'iPhone 12',
        'iPhone 12 Mini',
        'iPhone 12 Pro',
        'iPhone 12 Pro Max',
        'iPhone 13',
        'iPhone 13 Mini',
        'iPhone 13 Pro',
        'iPhone 13 Pro Max',
        'iPhone 14',
        'iPhone 14 Plus',
        'iPhone 14 Pro',
        'iPhone 14 Pro Max',
        'iPhone 15',
        'iPhone 15 Plus',
        'iPhone 15 Pro',
        'iPhone 15 Pro Max',
        'iPhone 16',
        'iPhone 16 Plus',
        'iPhone 16 Pro',
        'iPhone 16 Pro Max',
        'iPhone 16e',
        'iPhone 17',
        'iPhone 17 Air',
        'iPhone 17 Pro',
        'iPhone 17 Pro Max',
        'iPhone Air',
        'iPhone SE 2nd Gen',
        'iPhone SE 3rd Gen',
        'iPhone XR',
        'iPhone XS',
        'iPhone XS Max',
        'iPhone XS Max Global',
    ],

    'android' => [
        'ABCTECH' => ['X20'],
        'Alcatel' => ['V3 Ultra'],
        'Asus' => [
            'ZenFone Max Pro M1 (ZB602KL) (WW) / Max Pro M1 (ZB601KL) (IN)',
            'ZenFone Max Pro M2 (ZB631KL) (WW) / Max Pro M2 (ZB630KL) (IN)',
            'ASUS Zenfone 12 Ultra',
        ],
        'BALMUDA' => ['BALMUDA Phone'],
        'bq' => ['Aquaris X2', 'Aquaris X2 PRO'],
        'CIBER' => ['B610A115'],
        'Covia' => ['CP-G3'],
        'DOOGEE' => ['V30'],
        'dtab' => ['dtab d-51C'],
        'Energizer' => ['Hardcase H620S'],
        'Evolveo' => ['EVOLVEO StrongPhone G9'],
        'Fairphone' => ['Fairphone4'],
        'FCNT' => ['arrows BZ03', 'arrows N F-51C', 'arrows We A101FC'],
        'Fossil' => ['Fossil Gen 5 LTE'],
        'Gigaset' => ['Gigaset GX4 PRO'],
        'Google' => [
            'Pixel 2', 'Pixel 2 XL', 'Pixel 3', 'Pixel 3 XL', 'Pixel 3a', 'Pixel 3a XL',
            'Pixel 4', 'Pixel 4 XL', 'Pixel 4a', 'Pixel 4a (5G)', 'Pixel 5', 'Pixel 5a 5G',
            'Pixel 6', 'Pixel 6 Pro', 'Pixel 6a', 'Pixel 7', 'Pixel 7 Pro', 'Pixel 7a',
            'Pixel 8', 'Pixel 8 Pro', 'Pixel 9', 'Pixel 9 Pro', 'Pixel 9 Pro Fold',
            'Pixel 9 Pro XL', 'Google Pixel 9a', 'Pixel Fold',
            'Google Pixel 10', 'Google Pixel 10 Pro', 'Google Pixel 10 Pro Fold', 'Google Pixel 10 Pro XL',
        ],
        'Hamic' => ['MIELS'],
        'Hammer' => ['Hammer Blade 5G', 'Hammer Construction'],
        'Honeywell' => ['CT30XP', 'CT45 XP', 'CT47', 'EDA52', 'EDA5S'],
        'Honor' => [
            'Honor 90', 'Honor 400', 'Honor 400 Pro', 'Honor Magic4 Pro', 'HONOR Magic4 Pro',
            'HONOR Magic5 Pro', 'Honor Magic6 Pro', 'Honor Magic8 Pro Air', 'Magic8 Pro Air', 'FRI',
        ],
        'Hoozo' => ['HZ0010J'],
        'Huawei' => ['Mate 40 Pro', 'P40', 'P40 Pro'],
        'isafemobile' => ['IS540'],
        'KDDI' => ['AQUOS sense6s', 'AQUOS sense7', 'AQUOS wish2'],
        'KYOCERA' => [
            'Android One S9', 'Android One S10', 'DIGNO SANGA edition', 'DIGNO SX2', 'DIGNO SX3',
            'かんたんスマホ２', 'かんたんスマホ2+', 'かんたんスマホ3',
        ],
        'Lenovo' => ['d-42A', 'd-52C'],
        'LOGIC' => ['LOGIC MV01', 'LOGIC MV02'],
        'Microsoft' => ['Surface Pro 11'],
        'MiTAC' => ['N630', 'N672'],
        'Mobvoi' => ['TicWatch Pro 3 Cellular/LTE'],
        'Montblanc' => ['Summit 2+'],
        'Motorola' => [
            'moto g52j 5G', 'moto g53y 5G', 'Moto G53', 'Moto G53 5G', 'Moto G54',
            'Motorola Moto G Power (2026)', 'Edge 40', 'Edge 40 Neo', 'Edge 40 Pro', 'Edge 60',
            'Edge 60 Fusion', 'Edge 60 Pro', 'Edge+ Plus', 'Edge+ Plus (2022)', 'motorola razr',
            'motorola razr 2022', 'motorola razr 5G', 'Razr 2022', 'Razr 40 Ultra', 'Razr 50 Ultra',
            'Motorola Razr (2025)', 'Motorola Razr+ (2025)', 'Motorola Razr 60', 'Motorola Razr 60 Ultra',
            'Motorola Razr Fold', 'Signature',
        ],
        'Motorola Solutions' => ['MOTOTRBO ION'],
        'MyPhone' => ['Hammer Blade 3', 'Hammer Explorer Pro', 'Hammer_Explorer', 'myPhone Now eSIM'],
        'Nokia' => ['Nokia G60 5G', 'Nokia X30 5G', 'XR21'],
        'Nothing' => ['Nothing Phone 3a Pro', 'Phone (3)', 'Phone Pro'],
        'OnePlus' => ['OnePlus 11 5G', 'OnePlus 12', 'OnePlus 15', '13R', '13T'],
        'Oppo' => [
            'A5', 'A55s 5G', 'A77', 'CPH2247', 'Find N2 Flip', 'Find N5', 'Find X3 Pro',
            'Find X5', 'Find X5 Pro', 'Oppo Find X9', 'Oppo Find X9 Pro', 'OPPO Reno5 A',
            'OPPO Reno7 A', 'Reno14', 'Reno14 Pro', 'Reno15', 'Reno15 FS', 'Reno15 Pro Max',
            'Oppo Reno 15 Pro', 'Oppo Reno 15 Pro Max', 'OPPO Watch',
        ],
        'Premier' => ['TAB-7304-16G3GS'],
        'Rakuten' => ['C330', 'Rakuten BIG s', 'Rakuten Hand', 'Rakuten Hand5G', 'AQUOS sense6'],
        'Razer' => ['Razer Edge 5G'],
        'RealMe' => ['14 Pro+', 'GT 7', 'Realme 14 Pro+', 'RMX5070'],
        'Samsung' => [
            'Galaxy A23 5G', 'Galaxy A54 5G', 'Galaxy A55', 'Galaxy A56', 'A35', 'A36',
            'Galaxy 24 FE', 'Galaxy Note20', 'Galaxy Note20 5G', 'Galaxy Note20 Ultra', 'Galaxy Note20 Ultra 5G',
            'Galaxy S20 5G', 'Galaxy S20 Ultra 5G', 'Galaxy S20+ 5G', 'Galaxy S21 5G', 'Galaxy S21 Ultra 5G',
            'Galaxy S21+ 5G', 'Galaxy S22', 'Galaxy S22 5G', 'Galaxy S22 Ultra', 'Galaxy S22 Ultra 5G',
            'Galaxy S22+', 'Galaxy S22+ 5G', 'Galaxy S23', 'Galaxy S23 FE', 'Galaxy S23 Ultra', 'Galaxy S23+',
            'Galaxy S24', 'Galaxy S24 Ultra', 'Galaxy S24+', 'Galaxy S25', 'Galaxy S25 Edge', 'Galaxy S25 Ultra',
            'Galaxy S25+', 'Samsung Galaxy S26', 'Samsung Galaxy S26 Ultra', 'Samsung Galaxy S26+',
            'Galaxy Flip 5', 'Galaxy Flip7', 'Galaxy Fold 5', 'Galaxy Z Flip', 'Galaxy Z Flip 5G',
            'Galaxy Z Flip3 5G', 'Galaxy Z Flip4', 'Galaxy Z Flip7 FE', 'Samsung Galaxy Z Flip 7',
            'Galaxy Z Fold', 'Galaxy Z Fold2', 'Galaxy Z Fold3', 'Galaxy Z Fold4', 'Galaxy Z Fold7',
            'Samsung Galaxy Z Fold 7', 'Samsung Galaxy Z TriFold', 'Galaxy Watch4', 'Galaxy Watch4 Classic',
            'Galaxy Watch7 (LTE)', 'Galaxy Watch Ultra', 'Galaxy XCover7 Pro',
        ],
        'SG' => ['AQUOS R6', 'AQUOS R7', 'AQUOS sense7 plus', 'Leitz Phone 2', 'シンプルスマホ６'],
        'SGIN' => ['SGIN_E10M'],
        'Sharp' => [
            'AQUOS sense4 lite SH-RM15', 'Aquos Sense6', 'Aquos wish5', 'Aquos Wish6', 'Aquos Zero6',
            'SH-51F', 'AQUOS wish', 'AQUOS zero6',
        ],
        'Sony' => [
            'Xperia 1 IV', 'Xperia 1 V', 'Xperia 1 VII', 'Sony Xperia 1 VII', 'Xperia 10 III Lite',
            'Xperia 10 IV', 'Sony Xperia 10 VI', 'Xperia 5 IV', 'Xperia Ace III',
        ],
        'Surface' => ['Surface Duo', 'Surface Duo 2', 'Surface Pro 9'],
        'T-Mobile' => ['T-Mobile Revvl 7 Pro'],
        'TAG-TECH' => ['TAG-TAB-III'],
        'TCL' => ['60 XE NxtPaper', 'NxtPaper 70 Pro'],
        'Teclast' => ['X_EEA'],
        'TONE' => ['TONE_e22'],
        'VIKUSHA' => ['V-Z40'],
        'Vivo' => [
            'V29', 'V29 Lite 5G', 'V40', 'V50', 'Vivo V50', 'X90 Pro', 'X100 Pro', 'X200',
            'X200 Pro', 'X200s', 'X200T', 'Vivo X300', 'Vivo X300 Pro',
        ],
        'Vsmart' => ['Active 1'],
        'Xiaomi' => [
            '15 Ultra', 'Redmi Note 11 Pro 5G', 'Redmi Note 13 Pro', 'Redmi Note 13 Pro+',
            'Redmi Note 14 Pro', 'Redmi Note 14 Pro 5G', 'Redmi Note 14 Pro+', 'Redmi Note 14 Pro+ 5G',
            'Xiaomi 12T Pro', 'Xiaomi 13', 'Xiaomi 13 Lite', 'Xiaomi 13 Pro', 'Xiaomi 13T', 'Xiaomi 13T Pro',
            'Xiaomi 14', 'Xiaomi 14 Pro', 'Xiaomi 14 Ultra', 'Xiaomi 14T', 'Xiaomi 14T Pro', 'Xiaomi 15',
            'Xiaomi 15 Ultra', 'Xiaomi 15T', 'Xiaomi 15T Pro', 'Xiaomi Poco F8 Ultra', 'Xiaomi Poco X7',
        ],
        'Zebra' => [
            'EC55', 'ET56', 'TC26', 'TC57', 'TC58', 'TC77', 'Zebra Technologies L10',
            'Zebra Technologies MC2700', 'Zebra Technologies TC57x',
        ],
        'ZONKO' => ['K105_EEA'],
        'ZTE' => ['A103ZT', 'A202ZT', 'RAKUTEN BIG', 'ZR01', 'ZTE nubia Flip2'],
    ],
];
